---
- name: Generate config
  template:
    src: "k3s-config-master.yaml.j2"
    dest: "/etc/rancher/k3s/config.yaml"
    owner: root
    group: root
    mode: 0755
  notify: restart k3s

- name: Copy k3s service file
  register: k3s_service
  template:
    src: "k3s-master.service.j2"
    dest: "{{ k3s_systemd_dir }}/k3s.service"
    owner: root
    group: root
    mode: 0755
  notify: restart k3s

- name: Enable and start k3s (additional masters)
  systemd:
    name: k3s
    daemon_reload: yes
    state: started
    enabled: yes

- name: Create kubectl symlink
  file:
    src: /usr/local/bin/k3s
    dest: /usr/local/bin/kubectl
    state: link

- name: Create crictl symlink
  file:
    src: /usr/local/bin/k3s
    dest: /usr/local/bin/crictl
    state: link

- name: Create ctr symlink
  file:
    src: /usr/local/bin/k3s
    dest: /usr/local/bin/ctr
    state: link
