- name: Copy config file to user home directory
  copy:
    src: /etc/rancher/k3s/k3s.yaml
    dest: ~{{ ansible_user }}/.kube/config-{{ k3s_master_ip }}
    remote_src: yes
    owner: "{{ ansible_user }}"

- name: Replace https://localhost:6443 by https://master-ip:6443
  command: >-
    k3s kubectl config set-cluster default
      --server=https://{{ k3s_master_ip }}:6443
      --kubeconfig ~{{ ansible_user }}/.kube/config-{{ k3s_master_ip }}
  changed_when: true
