---

- name: Copy k3s agent service file
  template:
    src: "k3s-agent.service.j2"
    dest: "{{ k3s_systemd_dir }}/k3s-agent.service"
    owner: root
    group: root
    mode: 0755
  notify: restart k3s-agent

- name: enable k3s-agent
  systemd:
    name: k3s-agent
    daemon_reload: yes
    state: started
    enabled: yes

- name: Create crictl symlink
  file:
    src: /usr/local/bin/k3s
    dest: /usr/local/bin/crictl
    state: link

- name: Create ctr symlink
  file:
    src: /usr/local/bin/k3s
    dest: /usr/local/bin/ctr
    state: link
