---

- name: Copy k3s agent service file
  template:
    src: "k3s-agent.service.j2"
    dest: "{{ k3s_systemd_dir }}/k3s-agent.service"
    owner: root
    group: root
    mode: 0755
  notify: restart k3s-agent

- name: enable k3s-agent
  systemd:
    name: k3s-agent
    daemon_reload: yes
    state: started
    enabled: yes

- name: Create crictl symlink
  file:
    src: /usr/local/bin/k3s
    dest: /usr/local/bin/crictl
    state: link

- name: Create ctr symlink
  file:
    src: /usr/local/bin/k3s
    dest: /usr/local/bin/ctr
    state: link

- name: Configure ufw (master)
  when: k3s_ufw_enabled and k3s_ufw_enabled is defined
  block:
    - name: Allow specified ports in ufw (master)
      ufw:
        rule: allow
        port: "{{ item }}"
      with_items: "{{ k3s_node_allow_ports }}"

    - name: Allow specified subnets in ufw (master)
      ufw:
        rule: allow
        src: "{{ item }}"
      with_items: "{{ k3s_node_allow_subnets }}"

    - name: Set ufw policy to deny incoming
      ufw:
        default: deny
        direction: incoming

    - name: Set ufw policy to allow routed
      ufw:
        default: allow
        direction: routed

    - name: Set ufw policy to allow outgoing
      ufw:
        default: allow
        direction: outgoing

    - name: Enable ufw
      ufw:
        state: enabled
