- name: restart k3s
  systemd:
    name: k3s
    daemon_reload: yes
    state: restarted
    enabled: yes

- name: restart k3s-agent
  systemd:
    name: k3s-agent
    daemon_reload: yes
    state: restarted
    enabled: yes
