---
role_name_check: 1
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    groups:
      - k3s_master
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-ubuntu2204}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  options:
    diff: true
  inventory:
    group_vars:
      k3s_master:
        k3s_master: true
        k3s_master_extra_config:
          snapshotter: native
        k3s_extra_env:
          - INVOCATION_ID=
        # test adding additonal manifests
        k3s_extra_manifests:
          - name: kata
            state: present
            definition:
              apiVersion: node.k8s.io/v1
              kind: RuntimeClass
              metadata:
                name: kata
              handler: kata
        # test adding additional configfiles
        k3s_extra_config_files:
          - name: apiserver-tracing.yaml
            content: |
              apiVersion: apiserver.config.k8s.io/v1alpha1
              kind: TracingConfiguration
              endpoint: 127.0.0.1:4317
              samplingRatePerMillion: 100
        k3s_extra_packages:
          - open-iscsi
        k3s_gvisor: true
        k3s_crun: true
        k3s_gvisor_config:
          network: host
        k3s_master_disable:
          - metrics-server

  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}
