site_name: ansible k3s role
theme:
  name: material
  features:
    - content.code.copy
    - content.code.select
  palette:
    scheme: slate
    accent: indigo
plugins:
  - search

repo_url: https://github.com/rlex/ansible-role-k3s

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
